import 'normalize.css';
import { DefaultLayout } from "@/components/Layouts";
import { ThemeProvider } from "@/components/ThemeProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ThemeProvider>
      <html lang="ko">
        <body>
          <DefaultLayout>
            {children}
          </DefaultLayout>
        </body>
      </html>
    </ThemeProvider>
  );
}